services:
    spider_1:
        image: shopware6/spider
        environment:
            - SITEMAP_DOMAIN=domain.com
            - SITEMAP_URL=https://domain.com/sitemap.xml
        restart: unless-stopped

    spider_2:
        image: shopware6/spider
        environment:
            - SITEMAP_DOMAIN=domain.com
            - SITEMAP_URL=https://domain.com/de/sitemap.xml
        restart: unless-stopped
